name: Generate Version
outputs:
  version:
    value: ${{ steps.current-version.outputs.version }}
  branch:
    value: ${{ steps.current-branch.outputs.branch }}
runs:
  using: 'composite'
  steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Get current version
      id: current-version
      run: |
        GET_VERSION=$(node -p -e "require('./package.json').version")
        echo "version=${GET_VERSION}" >> $GITHUB_OUTPUT
        echo "version is ${GET_VERSION}"
      shell: bash
    - name: Get branch number
      id: current-branch
      run: |
        BRANCH=${{ github.base_ref }}
        IFS='/' read -ra BRANCH_PARTS <<< "$BRANCH"
        echo "branch=${BRANCH_PARTS[0]}" >> $GITHUB_OUTPUT
        echo "branch is ${BRANCH_PARTS[0]}"
      shell: bash
