name: Deploy AWS

on:
  push:
    branches:
      - "release/*"
      - "feature/*"
      - "master"
      - "develop"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

      # Aquí se puede agregar validaciones u otras generaciones

      - name: Build project
        run: npm run build
      - name: Save dist in state
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deployS3:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get dist from state
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ./dist
      - name: Upload dist to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: actions-demo
          destination_dir: dist
          source_dir: dist
      - name: Upload Showcase to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: actions-demo
          destination_dir: showcase
          source_dir: showcase
  deployArtifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get dist artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ./dist
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
      - name: Init session in CodeArtifact
        run: |
          aws codeartifact login --tool npm --repository actions-demo --domain demo --namespace actions
      - name: Get registry from CodeArtifact
        id: get-registry-endpoint
        run: |
          endpoint=$(aws codeartifact get-repository-endpoint --domain demo --repository actions-demo --format npm)
          echo "::set-output name=endpoint::$(echo $endpoint | jq -r '.repositoryEndpoint')"
      - name: Update .npmrc with registry
        run: |
          echo "registry=$(echo ${{ steps.get-registry-endpoint.outputs.endpoint }})" >> ~/.npmrc
      - name: Publish Library
        run: npm publish


