name: Deploy AWS

on:
  push:
    branches:
      - "release/*"
      - "feature/*"
      - "master"
      - "develop"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      # Aquí se puede agregar validaciones u otras generaciones

      - name: Build artifacts
        run: npm run build
      - name: Upload artifacts dist
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
      - name: Upload artifacts showcase
        uses: actions/upload-artifact@v3
        with:
          name: showcase-files
          path: showcase
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get dist artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ./dist
      - name: Get showcase artifacts
        uses: actions/download-artifact@v3
        with:
          name: showcase-files
          path: ./showcase
      - name: Upload dist to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: actions-demo
          destination_dir: dist
          source_dir: dist
      - name: Upload Showcase to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: actions-demo
          destination_dir: showcase
          source_dir: showcase
