name: Manual Revert to Last Tag

on:
  workflow_dispatch:

jobs:
  revert_to_last_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Revert to last tag
        run: |
          git checkout master
          
          PENULTIMATE_TAG=$(git tag --sort=-creatordate | grep -E "^v[0-9]+\.[0-9]+\.[0-9]+$" | sed -n '2p')
          echo "PENULTIMATE_TAG is $PENULTIMATE_TAG" 
          
          git reset --hard ${PENULTIMATE_TAG}
          git push --force origin master
