name: Manual Revert to Last Tag

on:
  workflow_dispatch:

jobs:
  revert_to_last_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Revert to last tag
        run: |
          git checkout master
          git reset --hard $(git describe --tags --abbrev=0)^
          git push --force origin master
